export const measureOptions = {
  position: "topleft",
  primaryLengthUnit: "meters",
  primaryAreaUnit: "sqmeters",
  activeColor: "#fd1100",
  completedColor: "#ff574b",
  labels: {
    measure: "Đo lường",
    measureDistancesAndAreas: "Đo khoảng cách và diện tích",
    createNewMeasurement: "Tạo mới phép đo",
    startCreating: "Thêm điểm lên bản đồ để tạo phép đo",
    finishMeasurement: "Kết thúc phép đo",
    lastPoint: "Điểm cuối",
    area: "Diện tích",
    perimeter: "Chu vi",
    pointLocation: "Tọa độ điểm",
    areaMeasurement: "Đo diện tích",
    linearMeasurement: "Đo đường",
    pathDistance: "Khoảng cách đường",
    centerOnArea: "Trung tâm",
    centerOnLine: "Trung tâm",
    centerOnLocation: "Trung tâm",
    cancel: "Hủy",
    delete: "Xóa",
    kilometers: "km",
    miles: "dặm",
    meters: "m",
    sqmeters: "m²",
  },
};
